export const Images = {
    background: require('../assets/images/backgroundColor.jpg'),
    welcomeBackground : require('../assets/background/welcomebackground.jpg'),
    introductionBackground: require('../assets/background/introductionbackground.jpg'),
    loginBackground: require('../assets/background/loginbackground.jpg'),
    map1: require('../assets/background/map1.jpg'),
    map2: require('../assets/background/map2.jpg'),
    logo: require('../assets/images/Logo.png'),
    logoTransparent: require('../assets/background/tLogo.png'),
    backgroundShape: require('../assets/images/backgroundShape.png'),
    map: require('../assets/images/Map.png'),
    user1: require('../assets/background/user1.png'),
    user2: require('../assets/background/user2.png'),
    user3: require('../assets/background/user3.png'),
    trace1: require('../assets/images/trace1.png'),
    trace2: require('../assets/images/trace2.png'),
    trace3: require('../assets/images/trace3.png'),
    upload: require('../assets/images/upload.png'),
    locationBlue: require('../assets/images/locationBlue.png'),
    locationWhite: require('../assets/images/locationWhite.png'),
    googleLogo: require('../assets/background/googleLogo.png'),
    facebookLogo: require('../assets/background/facebookLogo.png'),
    mapTabIcon1: require('../assets/background/mapTabIcon1.png'),
    mapTabIcon2: require('../assets/background/mapTabIcon2.png'),
    food1: require('../assets/background/food1.png'),
    food2: require('../assets/background/food2.png'),
    food3: require('../assets/background/food3.png'),
    food4: require('../assets/background/food4.png'),
    food5: require('../assets/background/food5.png'),
    mapLogo: require('../assets/background/mapLogo.png'),
    pencil: require('../assets/background/pencil.png'),
    telephone: require('../assets/background/telephone.png'),
    cancel: require('../assets/background/cancel.png'),
    mapCard : require('../assets/background/mapCard.png'),
    paypal: require('../assets/background/paypal.png'),
    masterCard: require('../assets/background/mastercard.png'),
    visa: require('../assets/background/visa.png'),
    police1: require('../assets/background/police1.jpg'),
    police2: require('../assets/background/police2.jpeg'),
    hospital1: require('../assets/background/hospital1.jpeg'),
    hospital2: require('../assets/background/hospital2.jpg'),
    emptyprofil: require('../assets/background/emptyprofil.png'),
    myplace: require('../assets/background/myplace.png'),
    emptyphoto: require('../assets/background/emptyphoto.jpg'),
    // arrow: require('../assets/background/locationarrow.png'),
    pharmacie1: require('../assets/background/pharmacie1.jpeg'),
    pharmacie2: require('../assets/background/pharmacie2.jpeg'),
    card: require('../assets/background/card.png'),
    sim: require('../assets/background/sim.png'),


  };
  