export default {
  geolocation: 'GEOLOCALISATION',
  myProfile: 'Mon profil',
  yes: 'Oui',
  password: 'Mot de passe',
  account: 'Compte',
  changePassword: 'Modifier mot de passe',
  changeLanguage: 'Langue',
  no: 'Non',
  newPass: 'Nouveau ...',
  pin: 'PIN',
  send: 'Envoyer',
  oldPassword: 'Mot de passe actuel',
  newPassword: 'Nouveau mot de passe',
  ConfirmNewPassword: 'Confirmation',
  ConfirmNewPassword1: 'Confirmer le mot de passe',
  update: 'Mise à jour',
  others: 'Autres',
  code: 'Code',
  uapdate: 'Modifier',
  cancel: 'Retour',
  logout: 'Déconnexion',
  settings: 'Paramètres',
  haveYouAccountTitle: 'Vous avez déjà un compte?',
  signInTitle: 'Connectez Vous!',
  textForgotPasword:
    ' Inscris ton mail pour recevoir les instructions afin de réinitiaisation',
  geolocateDescription:
    'Améliore ton experience en activant la geolocalisation de ton smartphone',
  insertYourCode:
    "Veuillez insérer le code envoyé dans l'email et modifier votre mot de passe",
  trendingMarket: 'À proximité',
  submit: 'Valider',
  codeInsert: "Veuillez inserer le code mentionné dans l'email",
  promotionCatalogue: 'Catalogues Promotionnelles',
  flashSales: 'Vente flash',
  category: 'Catégorie',
  search: 'Recherche',
  distance: 'Le plus proche',
  Catalogue: 'Catalogues',
  tellMeYourExperience: 'Raconte ton expérience',
  myFavorites: 'Mes favoris',
  market: 'Enseigne',
  send: 'Envoyer',
  cataloguNotFound: 'Aucun Catalogue trouvé',
  all: 'Tout',
  forgotPassword: 'Mot de passe oublié?',
  favoriteNotFound: 'Aucun élément trouvé',
  save: 'Enregistrer',
  forward: 'Transferer',
  profile: 'Profil',
  history: 'Historique',
  support: 'Support',
  home: 'Accueil',
  InroductionParag:
    'Loren ipsum is simply dummy text of the printng industry Loren fdsfsdfsdfsdxcwxwqs',
  LogIn: 'Connexion',
  emailPlaceHolder: 'Votre e-mail',
  emailRegister: 'E-mail',
  dontHaveAccount: "Vous n'avez pas de compte?",
  register: "S'inscrire",
  registerUpperCase: "S'INSCRIRE",
  registerTitle: 'Inscription',
  name: 'Nom',
  phoneNumberLabel: 'Numéro de Téléphone',
  next: 'SUIVANT',
  forwordMoney: 'Montant à transférer',
  sendCodeText: 'Nous avons envoyé un code à votre téléphone portable',
  verificationCodeText1: 'Veuillez vérifier votre numéro de portable',
  verificationCodeText2: 'continuez à réinitialiser votre mot de passe',
  phoneNumber: '071 ***** 12',
  youDontReceiveTitle: "Vous n'avez pas reçu?",
  clickHere: 'Cliquez Ici',
  putYourMessage: 'Tapez votre message',
  yourPasswordTitle: ' votre Mot de passe',
  reset: 'Réinitialiser',
  numberInsertTitle:
    'Veuillez saisir votre numéro pour recevoir un code pour créer un nouveau mot de passe',
  forgotPinLabel: 'PIN OUBLIÉ?',
};
